#pragma once

#include "a2_multi_edge_exact_cover.hpp"

#include <array>
#include <cstdint>
#include <stdexcept>
#include <vector>

// Cheap, sound parity-coherence precheck for the current-component-pair
// whole-block relaxation.
//
// Choose a root rho_i in each current forest component K_i and put
//
//     c_i(x) = d_Ki(rho_i,x) mod 2.
//
// In a completed weighted tree, designate one global distance-parity class
// as the smaller class, and let s_i be the intrinsic color of K_i belonging
// to that global class.  A rooted translated block generated by ports
// u in K_i, v in K_j and port-to-port distance L must satisfy
//
//     c_i(u) xor c_j(v) xor (L mod 2) = s_i xor s_j.       (PC)
//
// The size p of the designated class is forced by
//
//     p (n-p) = number of odd ranks in {1,...,target}.
//
// For order 18, target 153, this is p=7 (the familiar 7|11 profile).
// This checker computes, for every component pair, which of the two right
// sides in (PC) is supported by at least one internally injective translated
// block inside the current missing ranks.  It then asks whether one coherent
// choice of all s_i has the required mass and is supported by every pair.
// Failure is necessary evidence against a completion; passing remains only a
// relaxation because blocks chosen for different pairs need not be disjoint.

namespace multi_edge_parity_coherence {

struct Config {
    int max_components = 9;
};

struct Counters {
    std::uint64_t checks = 0;
    std::uint64_t skipped = 0;
    std::uint64_t component_pairs = 0;
    std::uint64_t port_patterns = 0;
    std::uint64_t candidate_lengths = 0;
    std::uint64_t no_relation_fail = 0;
    std::uint64_t profiles_tested = 0;
    std::uint64_t mass_profiles_tested = 0;
    std::uint64_t no_profile_fail = 0;
};

enum class Reason {
    pass,
    skipped,
    impossible_global_mass,
    no_pair_relation,
    no_coherent_profile
};

struct Outcome {
    bool possible = true;
    Reason reason = Reason::pass;
};

namespace detail {

inline bool coherent_profile_exists(
    const std::vector<std::array<int, 2>> &color_count,
    const std::vector<std::vector<unsigned>> &relation,
    int selected_class_size, Counters &counters) {
    const int component_count = static_cast<int>(color_count.size());
    if (component_count >= 63)
        throw std::logic_error("too many parity-coherence components");
    const std::uint64_t profile_count = 1ULL << component_count;
    for (std::uint64_t profile = 0; profile < profile_count; ++profile) {
        ++counters.profiles_tested;
        int mass = 0;
        for (int i = 0; i < component_count; ++i)
            mass += color_count[i][(profile >> i) & 1U];
        if (mass != selected_class_size) continue;
        ++counters.mass_profiles_tested;

        bool coherent = true;
        for (int i = 0; i < component_count && coherent; ++i) {
            for (int j = i + 1; j < component_count; ++j) {
                unsigned required = static_cast<unsigned>(
                    ((profile >> i) ^ (profile >> j)) & 1U);
                if (!(relation[i][j] & (1U << required))) {
                    coherent = false;
                    break;
                }
            }
        }
        if (coherent) return true;
    }
    return false;
}

} // namespace detail

class Checker {
    using Input = a2_multi_cover::Input;
    using RankMask = a2_multi_cover::RankMask;

    static unsigned relation_options(
        const Input &in, int i, int j,
        const std::array<int, 18> &intrinsic_color, Counters &counters) {
        const auto &a = in.components[i];
        const auto &b = in.components[j];
        unsigned relations = 0;

        // Do not deduplicate equal offset masks here unless all supported
        // port parities are retained.  For example, the two roots of an
        // odd-weight dimer have the same offset mask and opposite labels.
        for (int u : a) for (int v : b) {
            RankMask offsets;
            bool injective = true;
            for (int x : a) for (int y : b) {
                int offset = in.distance[x][u] + in.distance[v][y];
                if (offset < 0 || offset > in.target || offsets.get(offset)) {
                    injective = false;
                    break;
                }
                offsets.set(offset);
            }
            if (!injective) continue;
            ++counters.port_patterns;

            RankMask allowed_length = in.missing;
            for (int offset = 0; offset <= in.target; ++offset)
                if (offsets.get(offset))
                    allowed_length &= in.missing.shifted_down(offset);
            allowed_length.clear_outside(1, in.target);

            const int port_parity = intrinsic_color[u] ^ intrinsic_color[v];
            counters.candidate_lengths += allowed_length.count();
            // Bit number and rank have the same parity in every 64-bit word.
            // We need only parity existence here, not the individual lengths.
            constexpr std::uint64_t even_bits = 0x5555555555555555ULL;
            constexpr std::uint64_t odd_bits = 0xAAAAAAAAAAAAAAAAULL;
            bool has_even = false, has_odd = false;
            for (int word = 0; word < RankMask::words; ++word) {
                has_even = has_even || (allowed_length.x[word] & even_bits);
                has_odd = has_odd || (allowed_length.x[word] & odd_bits);
            }
            if (has_even) relations |= 1U << port_parity;
            if (has_odd) relations |= 1U << (port_parity ^ 1);
            if (relations == 3U) return relations;
        }
        return relations;
    }

  public:
    Outcome check(const Input &in, const Config &config,
                  Counters &counters) const {
        ++counters.checks;
        if (in.n < 1 || in.n > 18)
            throw std::logic_error("parity-coherence vertex count out of range");
        if (in.target < 1 ||
            in.target >= 64 * a2_multi_cover::RankMask::words)
            throw std::logic_error("parity-coherence target out of range");

        const int component_count = static_cast<int>(in.components.size());
        if (component_count <= 1) return {true, Reason::pass};
        if (component_count > config.max_components) {
            ++counters.skipped;
            return {true, Reason::skipped};
        }

        // There is at most one solution p <= n/2 to this quadratic.
        const int odd_rank_count = (in.target + 1) / 2;
        int selected_class_size = -1;
        for (int p = 0; p <= in.n / 2; ++p) {
            if (p * (in.n - p) == odd_rank_count) {
                selected_class_size = p;
                break;
            }
        }
        if (selected_class_size < 0)
            return {false, Reason::impossible_global_mass};

        std::array<int, 18> intrinsic_color{};
        std::vector<std::array<int, 2>> color_count(component_count);
        std::array<unsigned char, 18> seen{};
        int vertex_count = 0;
        for (int i = 0; i < component_count; ++i) {
            if (in.components[i].empty())
                throw std::logic_error("empty forest component");
            int root = in.components[i][0];
            for (int v : in.components[i]) {
                if (v < 0 || v >= in.n || seen[v])
                    throw std::logic_error("invalid forest component partition");
                seen[v] = 1;
                ++vertex_count;
                intrinsic_color[v] = in.distance[root][v] & 1;
                ++color_count[i][intrinsic_color[v]];
            }
            for (int x : in.components[i]) for (int y : in.components[i])
                if ((intrinsic_color[x] ^ intrinsic_color[y]) !=
                    (in.distance[x][y] & 1))
                    throw std::logic_error("inconsistent weighted parity coloring");
        }
        if (vertex_count != in.n)
            throw std::logic_error("forest components do not cover vertices");

        std::vector<std::vector<unsigned>> relation(
            component_count, std::vector<unsigned>(component_count, 0));
        for (int i = 0; i < component_count; ++i) {
            for (int j = i + 1; j < component_count; ++j) {
                ++counters.component_pairs;
                relation[i][j] = relation_options(
                    in, i, j, intrinsic_color, counters);
                if (!relation[i][j]) {
                    ++counters.no_relation_fail;
                    return {false, Reason::no_pair_relation};
                }
            }
        }

        // s_i is the intrinsic color placed in the selected (smaller) global
        // class.  Enumerating all profiles avoids the common unsound shortcut
        // of fixing s_0 while retaining only mass p instead of p or n-p.
        if (detail::coherent_profile_exists(
                color_count, relation, selected_class_size, counters))
            return {true, Reason::pass};

        ++counters.no_profile_fail;
        return {false, Reason::no_coherent_profile};
    }
};

} // namespace multi_edge_parity_coherence
